import Foundation

/// Hindi for everything the coach says, keyed by the English it is written as elsewhere.
///
/// Instructions use the ordinary respectful imperative (करें), which is how a teacher speaks to a
/// class. Pose names are the Sanskrit ones in Devanagari rather than a transliteration, because
/// that is what the pose is called and what a Hindi voice can actually pronounce.
///
/// Adding a cue to `AsanaLibrary` without adding it here is not an error: it will simply be
/// spoken in English. `Speech.untranslated()` lists anything missing, and Pose Lab shows the
/// count while `DevFlags.isDevelopmentBuild` is on.
enum SpeechHindi {
    static let asanaNames: [String: String] = [
        "mountain": "ताड़ासन",
        "chair": "उत्कटासन",
        "warrior-one": "वीरभद्रासन एक",
        "warrior-two": "वीरभद्रासन दो",
        "triangle": "त्रिकोणासन",
        "goddess": "उत्कट कोणासन",
        "tree": "वृक्षासन",
        "warrior-three": "वीरभद्रासन तीन",
        "half-moon": "अर्ध चंद्रासन",
        "dancer": "नटराजासन",
        "plank": "फलकासन",
        "side-plank": "वसिष्ठासन",
        "boat": "नावासन",
        "down-dog": "अधोमुख श्वानासन",
        "cobra": "भुजंगासन",
        "bridge": "सेतुबंध सर्वांगासन",
        "locust": "शलभासन",
        "camel": "उष्ट्रासन",
        "forward-fold": "उत्तानासन",
        "half-fold": "अर्ध उत्तानासन",
        "low-lunge": "अंजनेयासन",
        "seated-fold": "पश्चिमोत्तानासन",
        "child": "बालासन",
        "corpse": "शवासन",
    ]

    static let lines: [String: String] = [
        // MARK: - Alignment cues

        "Bend your elbows to right angles, palms forward": "कोहनियाँ समकोण पर मोड़ें, हथेलियाँ सामने रखें",
        "Bend your front knee deeper": "अगला घुटना और ज़्यादा मोड़ें",
        "Bend your front knee toward a right angle": "अगला घुटना समकोण तक मोड़ें",
        "Bend your lifted knee and press the foot into your hand": "उठा हुआ घुटना मोड़ें और पैर को हाथ में दबाएँ",
        "Bring your feet under your hips": "पैरों को कूल्हों के नीचे लाएँ",
        "Bring your hips into one straight line": "कूल्हों को एक सीध में लाएँ",
        "Bring your torso parallel to the floor": "धड़ को ज़मीन के समानांतर लाएँ",
        "Come up a little": "थोड़ा ऊपर उठें",
        "Come up a little, keep your knees above your ankles": "थोड़ा ऊपर उठें, घुटने टखनों के ऊपर रखें",
        "Draw your lifted foot higher up your leg": "उठे हुए पैर को जाँघ पर और ऊपर ले जाएँ",
        "Ease up, keep your knee above your ankle": "थोड़ा ढीला छोड़ें, घुटना टखने के ऊपर रखें",
        "Fold deeper from your hips, not your waist": "कमर से नहीं, कूल्हों से और झुकें",
        "Fold forward from the hips, over your legs": "कूल्हों से आगे झुकें, पैरों के ऊपर",
        "Fold your chest down toward your thighs": "छाती को जाँघों की ओर नीचे झुकाएँ",
        "Hips back, chest forward, back flat as a table": "कूल्हे पीछे, छाती आगे, पीठ मेज़ जैसी सपाट",
        "Hold your body level with the floor": "शरीर को ज़मीन के समानांतर रखें",
        "Hold your body on a long diagonal": "शरीर को एक लंबी तिरछी रेखा में रखें",
        "Keep both arms straight": "दोनों बाहें सीधी रखें",
        "Keep both legs straight": "दोनों पैर सीधे रखें",
        "Keep your hips and legs down on the floor": "कूल्हे और पैर ज़मीन पर टिके रहने दें",
        "Keep your legs long and straight behind you": "पैर पीछे लंबे और सीधे रखें",
        "Keep your legs straight and your feet flexed": "पैर सीधे रखें और पंजे अपनी ओर खींचें",
        "Keep your legs straight as they lift": "उठाते समय पैर सीधे रखें",
        "Keep your spine tall and your chest open": "रीढ़ सीधी और छाती खुली रखें",
        "Kneel with your hips over your knees": "घुटनों के बल बैठें, कूल्हे घुटनों के ऊपर",
        "Lengthen through your hips, don't crunch your low back": "कूल्हों से लंबाई बनाएँ, कमर को न दबाएँ",
        "Lengthen your spine parallel to the floor": "रीढ़ को ज़मीन के समानांतर लंबा करें",
        "Let your back knee rest under your hip": "पिछला घुटना कूल्हे के नीचे टिकने दें",
        "Let your hands drop toward the floor": "हाथों को ज़मीन की ओर छोड़ दें",
        "Let your hips settle down": "कूल्हों को नीचे बैठने दें",
        "Let your legs relax out straight": "पैरों को सीधा फैलाकर ढीला छोड़ें",
        "Let your torso hang down toward the floor": "धड़ को ज़मीन की ओर लटकने दें",
        "Let your whole body rest long on the floor": "पूरे शरीर को ज़मीन पर लंबा फैलाकर टिकाएँ",
        "Level your hips": "कूल्हों को बराबर रखें",
        "Level your shoulders": "कंधों को बराबर रखें",
        "Lie flat on your back": "पीठ के बल सीधे लेट जाएँ",
        "Lift both legs off the floor": "दोनों पैर ज़मीन से ऊपर उठाएँ",
        "Lift your back foot higher": "पिछला पैर और ऊपर उठाएँ",
        "Lift your back foot to hip height": "पिछला पैर कूल्हे की ऊँचाई तक उठाएँ",
        "Lift your chest and arch back gently": "छाती उठाएँ और धीरे से पीछे झुकें",
        "Lift your chest and roll your shoulders back": "छाती उठाएँ और कंधे पीछे घुमाएँ",
        "Lift your chest and stand your torso up": "छाती उठाएँ और धड़ सीधा करें",
        "Lift your chest instead of folding forward": "आगे झुकने के बजाय छाती उठाएँ",
        "Lift your chest off the floor": "छाती ज़मीन से ऊपर उठाएँ",
        "Lift your chest tall, don't dump into your low back": "छाती ऊँची उठाएँ, कमर पर भार न डालें",
        "Lift your feet above hip height": "पैरों को कूल्हों से ऊपर उठाएँ",
        "Lift your foot off the floor": "पैर ज़मीन से ऊपर उठाएँ",
        "Lift your hips higher": "कूल्हे और ऊपर उठाएँ",
        "Lift your hips into one straight line": "कूल्हों को उठाकर एक सीध में लाएँ",
        "Lift your hips up and back into a long V": "कूल्हे ऊपर और पीछे उठाकर लंबा V बनाएँ",
        "Lift your top leg to hip height": "ऊपर वाला पैर कूल्हे की ऊँचाई तक उठाएँ",
        "Make a V: lift your chest and your legs together": "V बनाएँ, छाती और पैर एक साथ उठाएँ",
        "Open your arms into one long line": "बाहों को खोलकर एक लंबी रेखा बनाएँ",
        "Open your chest, torso level with the floor": "छाती खोलें, धड़ ज़मीन के समानांतर",
        "Press your feet down and lift": "पैरों से ज़मीन दबाएँ और ऊपर उठें",
        "Press your hips forward as you arch back": "पीछे झुकते हुए कूल्हे आगे दबाएँ",
        "Reach both arms level with the floor": "दोनों बाहें ज़मीन के समानांतर फैलाएँ",
        "Reach both arms overhead": "दोनों बाहें सिर के ऊपर उठाएँ",
        "Reach your arms forward, level with the floor": "बाहें आगे फैलाएँ, ज़मीन के समानांतर",
        "Reach your arms overhead": "बाहें सिर के ऊपर उठाएँ",
        "Reach your arms straight back": "बाहें सीधी पीछे की ओर फैलाएँ",
        "Reach your arms up alongside your ears": "बाहें कानों के बराबर ऊपर उठाएँ",
        "Reach your hands back toward your heels": "हाथ पीछे एड़ियों की ओर ले जाएँ",
        "Reach your hands toward your feet": "हाथ पैरों की ओर बढ़ाएँ",
        "Reach your heels down and straighten your legs": "एड़ियाँ नीचे ले जाएँ और पैर सीधे करें",
        "Reach your lifted leg back in line with your body": "उठा हुआ पैर शरीर की सीध में पीछे फैलाएँ",
        "Reach your top arm straight up": "ऊपर वाली बाँह सीधी ऊपर उठाएँ",
        "Rest your hands on your shins": "हाथ पिंडलियों पर टिकाएँ",
        "Sink lower into the lunge": "लंज में और नीचे बैठें",
        "Sink your hips lower, knees tracking over your toes": "कूल्हे और नीचे ले जाएँ, घुटने पंजों की सीध में",
        "Sit down on the floor with your legs long": "ज़मीन पर बैठें और पैर लंबे फैलाएँ",
        "Sit lower, bend your knees more": "और नीचे बैठें, घुटने ज़्यादा मोड़ें",
        "Sit your hips back toward your heels": "कूल्हे पीछे एड़ियों की ओर ले जाएँ",
        "Stack your front knee over your ankle": "अगला घुटना टखने के ठीक ऊपर रखें",
        "Stack your knees over your ankles": "घुटने टखनों के ठीक ऊपर रखें",
        "Stack your shoulders over your hips, don't lean": "कंधे कूल्हों के ऊपर रखें, झुकें नहीं",
        "Stack your top arm over the bottom one": "ऊपर वाली बाँह नीचे वाली के ठीक ऊपर रखें",
        "Stand tall on your standing leg": "जिस पैर पर खड़े हैं उस पर तनकर खड़े हों",
        "Stand tall, don't lean out to the side": "सीधे खड़े हों, बगल में न झुकें",
        "Stand tall, stack your shoulders over your hips": "सीधे खड़े हों, कंधे कूल्हों के ऊपर रखें",
        "Step your feet wider apart": "पैरों को और चौड़ा फैलाएँ",
        "Straighten your arms": "बाहें सीधी करें",
        "Straighten your arms and press the floor away": "बाहें सीधी करें और ज़मीन को दबाएँ",
        "Straighten your arms, shoulders over wrists": "बाहें सीधी करें, कंधे कलाइयों के ऊपर",
        "Straighten your back leg": "पिछला पैर सीधा करें",
        "Straighten your legs": "पैर सीधे करें",
        "Straighten your legs and press your heels back": "पैर सीधे करें और एड़ियाँ पीछे दबाएँ",
        "Straighten your legs as much as feels kind": "जितना आराम से हो सके उतने पैर सीधे करें",
        "Straighten your legs if your back allows": "अगर पीठ इजाज़त दे तो पैर सीधे करें",
        "Straighten your legs without locking your knees": "पैर सीधे करें पर घुटने जकड़ें नहीं",
        "Straighten your lifted leg": "उठा हुआ पैर सीधा करें",
        "Straighten your standing leg": "जिस पैर पर खड़े हैं उसे सीधा करें",
        "Straighten your supporting arm": "सहारा देने वाली बाँह सीधी करें",
        "Sweep your arms overhead": "बाहें घुमाकर सिर के ऊपर ले जाएँ",
        "Tip your chest forward as the leg lifts back": "पैर पीछे उठाते हुए छाती आगे झुकाएँ",
        "Tip your torso sideways over your front leg": "धड़ को अगले पैर के ऊपर बगल में झुकाएँ",
        "Walk your feet closer so your shins stand upright": "पैर पास लाएँ ताकि पिंडलियाँ सीधी खड़ी रहें",
        "Walk your hands and feet further apart": "हाथ और पैर और दूर ले जाएँ",
        "Walk your hands forward and rest": "हाथ आगे बढ़ाएँ और आराम करें",

        // MARK: - Held and settled

        "Hold and breathe": "रुकें और साँस लेते रहें",
        "That's the shape - hold it": "यही मुद्रा है, इसे बनाए रखें",

        // MARK: - Getting into each pose

        "Stand with your feet under your hips, weight even on both.": "पैर कूल्हों के नीचे रखकर खड़े हों, भार दोनों पर बराबर।",
        "Feet together, then bend your knees and sit your hips back.": "पैर मिलाएँ, फिर घुटने मोड़कर कूल्हे पीछे ले जाएँ।",
        "Step your left foot forward into a long lunge.": "बायाँ पैर आगे बढ़ाकर लंबा लंज बनाएँ।",
        "Step wide, turn your left foot out and your back foot in slightly.": "चौड़ा कदम लें, बायाँ पैर बाहर और पिछला पैर थोड़ा अंदर घुमाएँ।",
        "From a wide stance, turn your left foot out and keep both legs straight.": "चौड़े खड़े होकर बायाँ पैर बाहर घुमाएँ और दोनों पैर सीधे रखें।",
        "Step wide and turn your toes out to about forty-five degrees.": "चौड़ा कदम लें और पंजे लगभग पैंतालीस डिग्री बाहर घुमाएँ।",
        "Stand tall, then shift your weight onto your right foot.": "सीधे खड़े हों, फिर भार दाएँ पैर पर ले जाएँ।",
        "From standing, shift onto your right foot and hinge forward at the hip.": "खड़े होकर दाएँ पैर पर आएँ और कूल्हे से आगे झुकें।",
        "From a lunge, reach your bottom hand to the floor ahead of your front foot.": "लंज से नीचे वाला हाथ अगले पैर के आगे ज़मीन पर रखें।",
        "Stand on your right foot and bend your left knee behind you.": "दाएँ पैर पर खड़े हों और बायाँ घुटना पीछे मोड़ें।",
        "Come to your hands and knees, then step both feet back.": "हाथों और घुटनों पर आएँ, फिर दोनों पैर पीछे ले जाएँ।",
        "From plank, roll onto the outside edge of your left foot.": "प्लैंक से बाएँ पैर के बाहरी किनारे पर घूमें।",
        "Sit down, lean back and lift your feet off the floor.": "बैठ जाएँ, पीछे झुकें और पैर ज़मीन से उठाएँ।",
        "From hands and knees, tuck your toes and lift your hips up and back.": "हाथों और घुटनों से पंजे मोड़ें और कूल्हे ऊपर और पीछे उठाएँ।",
        "Lie on your front with your hands under your shoulders.": "पेट के बल लेटें, हाथ कंधों के नीचे रखें।",
        "Lie on your back and walk your heels close to your hips.": "पीठ के बल लेटें और एड़ियाँ कूल्हों के पास लाएँ।",
        "Lie on your front with your arms alongside your body.": "पेट के बल लेटें, बाहें शरीर के बगल में रखें।",
        "Kneel with your hips stacked over your knees, hips width apart.": "घुटनों के बल बैठें, कूल्हे घुटनों के ऊपर, कूल्हों जितनी दूरी पर।",
        "Stand with your feet hip width apart, hands on your hips.": "पैर कूल्हों जितनी दूरी पर रखकर खड़े हों, हाथ कमर पर।",
        "From a forward fold, slide your hands to your shins.": "आगे झुकी अवस्था से हाथ पिंडलियों तक सरकाएँ।",
        "Step your left foot forward and lower your back knee to the floor.": "बायाँ पैर आगे बढ़ाएँ और पिछला घुटना ज़मीन पर टिकाएँ।",
        "Sit with your legs straight out and your feet flexed.": "पैर सीधे फैलाकर बैठें और पंजे अपनी ओर खींचें।",
        "Kneel and bring your big toes together, knees as wide as feels good.": "घुटनों के बल बैठें, अंगूठे मिलाएँ, घुटने आराम के अनुसार चौड़े।",
        "Lie on your back with your legs long and slightly apart.": "पीठ के बल लेटें, पैर लंबे और थोड़े अलग।",

        // MARK: - Framing and facing

        "Step into view": "कैमरे के सामने आएँ",
        "Get your whole body in frame": "पूरा शरीर फ्रेम में लाएँ",
        "Step back from the camera": "कैमरे से पीछे हटें",
        "Step closer to the camera": "कैमरे के पास आएँ",
        "Move to the middle of the frame": "फ्रेम के बीच में आएँ",
        "Nicely framed": "फ्रेम ठीक है",
        "Face the camera": "कैमरे की ओर मुँह करें",
        "Turn side-on to the camera": "कैमरे की ओर बगल करके खड़े हों",

        // MARK: - Body scan

        "Stand tall": "सीधे खड़े हों",
        "Turn side-on": "बगल में घूमें",
        "Reach up": "हाथ ऊपर उठाएँ",
        "Fold forward": "आगे झुकें",
        "Squat down": "नीचे बैठें",
        "Balance, left foot": "बाएँ पैर पर संतुलन",
        "Balance, right foot": "दाएँ पैर पर संतुलन",
        "Bend left": "बाईं ओर झुकें",
        "Bend right": "दाईं ओर झुकें",
        "Face the camera and stand naturally": "कैमरे की ओर मुँह करके सहज खड़े हों",
        "Turn to your right and stand naturally": "दाईं ओर घूमकर सहज खड़े हों",
        "Face the camera and reach both arms overhead": "कैमरे की ओर मुँह करके दोनों बाहें सिर के ऊपर उठाएँ",
        "Side-on, fold forward as far as is comfortable": "बगल में खड़े होकर जितना सहज हो उतना आगे झुकें",
        "Side-on, squat as low as you comfortably can": "बगल में खड़े होकर जितना सहज हो उतना नीचे बैठें",
        "Stand on your left foot only": "केवल बाएँ पैर पर खड़े हों",
        "Stand on your right foot only": "केवल दाएँ पैर पर खड़े हों",
        "Face the camera and lean over to your left": "कैमरे की ओर मुँह करके बाईं ओर झुकें",
        "Face the camera and lean over to your right": "कैमरे की ओर मुँह करके दाईं ओर झुकें",

        // MARK: - Balance test

        "Stand on your left foot when the countdown ends.": "गिनती पूरी होते ही बाएँ पैर पर खड़े हों।",
        "Go. Hold as long as you can.": "शुरू करें। जितनी देर हो सके रुके रहें।",
        "Good. Now the other side: stand on your right foot.": "बढ़िया। अब दूसरी ओर, दाएँ पैर पर खड़े हों।",
        "Test complete.": "जाँच पूरी हुई।",

        // MARK: - Breathing

        "Breathe in": "साँस लें",
        "Breathe out": "साँस छोड़ें",
        "Hold": "रोकें",
        "Even Breath": "सम श्वास",
        "Long Exhale": "लंबा रेचक",
        "Box Breath": "चतुर्भुज श्वास",
        "4-7-8": "चार, सात, आठ",
        "Ocean Breath": "उज्जायी श्वास",
        "Breathe in and out for the same count.": "समान गिनती में साँस लें और छोड़ें।",
        "Breathe out for twice as long as you breathe in.": "साँस लेने से दोगुनी देर तक साँस छोड़ें।",
        "In, hold, out, hold, all for four.": "लें, रोकें, छोड़ें, रोकें, सब चार की गिनती में।",
        "In for four, hold for seven, out for eight.": "चार तक लें, सात तक रोकें, आठ तक छोड़ें।",
        "Slow breathing with a soft hiss at the back of the throat.": "गले के पिछले हिस्से में हल्की आवाज़ के साथ धीमी साँस।",
    ]
}
